### PR TITLE
OpenBSD 7.2

### PR DESCRIPTION
**Pull request by jage**
Box imports and runs as expected.

### CODE REVIEW

**Review by Chrizpy — APPROVED** [review]
:shipit:

**Comment by dentarg** [comment]
Will you upload to Vagrant Cloud too? :-)

**Comment by Chrizpy** [comment]
> Will you upload to Vagrant Cloud too? :-)

You got it! 📦 🚀

**Comment by dentarg** [comment]
Sweet! Posting the link here for completeness: https://app.vagrantup.com/twingly/boxes/openbsd-7.2-amd64

**Pull request merged**
