### PR TITLE
Update FreeBSD box to 10.2

### LINKED ISSUE #2: FreeBSD 10.2 box
It's what we used these days (we have a 10.1 box already).

### PR DESCRIPTION
**Pull request by jage**
Uploaded to https://atlas.hashicorp.com/twingly/boxes/freebsd-10.2-amd64

Close #2

### CODE REVIEW

**Comment by walro** [comment]
Should we tag the commit of the old 10.1 box?

**Comment by dentarg** [comment]
Yes, I think we should tag

**Comment by walro** [comment]
IIRC @dentarg had some ideas on how to keep track of things like this

**Comment by dentarg** [comment]
Yeah, like https://github.com/tmatilai/packer-openbsd/releases

**Comment by dentarg** [comment]
Or like we have done: https://github.com/twingly/boxes/tags :)

**Comment by walro** [comment]
Oh, hehe.

**Comment by walro** [comment]
LGTM! (Guess we should add a release/tag too then).

**Comment by jage** [comment]
I'll tag. Not sure I like releases in this repository since we have multiple boxes.

**Comment by dentarg** [comment]
What's the problem with releases and multiple boxes?

**Comment by jage** [comment]
> What's the problem with releases and multiple boxes?

What's interesting here is how a box was built. The Atlas version should link to a commit (tag), not the other way around. We don't release boxes from GitHub, we release them through Atlas.

Once #1 is merged we'll have multiple boxes with separate versions/release cycles. I don't see the point in creating some "fake" releases here. I think it's important that we link which packer config was used when building the box though.

**Comment by dentarg** [comment]
Yeah, I understand... but in my mind there would be no new releases for e.g. the FreeBSD 10.1 box once we have FreeBSD 10.2 in master, thus not creating that "problem" :)

**Comment by jage** [comment]
> Yeah, I understand... but in my mind there would be no new releases off e.g. the FreeBSD 10.1 box once we have FreeBSD 10.2 in master, thus not creating that "problem" :)

But what would be gain with creating a release?

**Comment by dentarg** [comment]
I like the releases though, because we can add information to them, e.g. a link to the specific version on Atlas.

**Comment by jage** [comment]
> I like the releases though, because we can add information to them, e.g. a link to the specific version on Atlas.

It's possible to annotate and link to tags as well.

**Pull request merged**
