### PR TITLE
OpenBSD 7.1

### PR DESCRIPTION
**Pull request by jage**
https://www.openbsd.org/plus71.html

### CODE REVIEW

**Comment by jage** [comment]
Tested box with Vagrant, seems to work fine. :)

**Comment by roback** [comment]
> Tested box with Vagrant, seems to work fine. :)

Seems to work fine for me too! I'll go ahead and merge/upload it to Vagrant cloud :)

**Comment by roback** [comment]
Released! https://app.vagrantup.com/twingly/boxes/openbsd-7.1-amd64/versions/1.0.0

**Comment by jage** [comment]
Awesome, thanks! :)

**Pull request merged**
