### PR TITLE
Update to OpenBSD 6.2

### LINKED ISSUE #16: OpenBSD 6.2
Released today: https://www.openbsd.org/62.html

### PR DESCRIPTION
**Pull request by jage**
Close #16

### CODE REVIEW

**Comment by jage** [comment]
Just updated the version number and checksum, haven't verified the box yet. But it builds at least.

**Comment by dentarg** [comment]
I can't download the ISO, from my home (Bahnhof), tried 3 times, always stops at around 30%:

```
$ packer build template.json
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: https://ftp.eu.openbsd.org/pub/OpenBSD/6.2/amd64/install62.iso
    virtualbox-iso: Download progress: 0%
    virtualbox-iso: Download progress: 0%
    virtualbox-iso: Download progress: 2%
    virtualbox-iso: Download progress: 5%
    virtualbox-iso: Download progress: 8%
    virtualbox-iso: Download progress: 11%
    virtualbox-iso: Download progress: 14%
    virtualbox-iso: Download progress: 16%
    virtualbox-iso: Download progress: 19%
    virtualbox-iso: Download progress: 22%
    virtualbox-iso: Download progress: 25%
    virtualbox-iso: Download progress: 28%
    virtualbox-iso: Download progress: 30%
    virtualbox-iso: Download progress: 33%
    virtualbox-iso: Error downloading: unexpected EOF
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.
```

I tried manually, and I can see that `wget` has to re-try the download. I guess packer doesn't have support for that.

```
$ wget https://ftp.eu.openbsd.org/pub/OpenBSD/6.2/amd64/install62.iso
--2017-12-06 22:33:35--  https://ftp.eu.openbsd.org/pub/OpenBSD/6.2/amd64/install62.iso
Resolving ftp.eu.openbsd.org... 193.156.26.18, 2001:700:3:4017::100
Connecting to ftp.eu.openbsd.org|193.156.26.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 346277888 (330M) [application/octet-stream]
Saving to: 'install62.iso'

install62.iso                                  30%[===========================>                                                                   ]  99.70M  1.50MB/s    in 67s

2017-12-06 22:34:42 (1.48 MB/s) - Connection closed at byte 104546304. Retrying.

--2017-12-06 22:34:43--  (try: 2)  https://ftp.eu.openbsd.org/pub/OpenBSD/6.2/amd64/install62.iso
Connecting to ftp.eu.openbsd.org|193.156.26.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 346277888 (330M), 241731584 (231M) remaining [application/octet-stream]
Saving to: 'install62.iso'

install62.iso                                  64%[++++++++++++++++++++++++++++================================>                                  ] 213.31M  1.78MB/s    in 69s

2017-12-06 22:35:52 (1.65 MB/s) - Connection closed at byte 223674368. Retrying.

--2017-12-06 22:35:54--  (try: 3)  https://ftp.eu.openbsd.org/pub/OpenBSD/6.2/amd64/install62.iso
Connecting to ftp.eu.openbsd.org|193.156.26.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 346277888 (330M), 122603520 (117M) remaining [application/octet-stream]
Saving to: 'install62.iso'

install62.iso                                  99%[+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++================================> ] 327.67M  2.03MB/s    in 65s

2017-12-06 22:36:59 (1.77 MB/s) - Connection closed at byte 343588864. Retrying.

--2017-12-06 22:37:02--  (try: 4)  https://ftp.eu.openbsd.org/pub/OpenBSD/6.2/amd64/install62.iso
Connecting to ftp.eu.openbsd.org|193.156.26.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 346277888 (330M), 2689024 (2.6M) remaining [application/octet-stream]
Saving to: 'install62.iso'

install62.iso                                 100%[++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++>] 330.24M  5.66MB/s    in 0.5s

2017-12-06 22:37:02 (5.66 MB/s) - 'install62.iso' saved [346277888/346277888]
```



I tried `wget`:ing https://ftp.fr.openbsd.org/pub/OpenBSD/6.2/amd64/install62.iso and that worked without any retries.

I know the openup script uses `ftp.fr.openbsd.org` as their mirror, should we switch?

**Comment by jage** [comment]
> I know the openup script uses ftp.fr.openbsd.org as their mirror, should we switch?

Sure.

**Comment by jage** [comment]
Heh, ftp.fr.openbsd.org is super slow for me, 27 KB/s from Telia. Weird.

**Comment by dentarg** [comment]
I changed to ftp.fr.openbsd.org yesterday evening, but no success. Downloading hasn't completed, seems it is stuck on 98%. `packer` still emits output tho: `virtualbox-iso: Download progress: 98%`. Guess it's another bug in packer...

**Comment by dentarg** [comment]
Now trying with fastly.cdn.openbsd.org, got it from https://www.openbsd.org/ftp.html

**Comment by dentarg** [comment]
Downloading worked and was quick, I think we should go with fastly.cdn.openbsd.org.

**Comment by jage** [comment]
> Downloading worked and was quick, I think we should go with fastly.cdn.openbsd.org.

Sure, I've used it on my private servers. Pretty fast usually, and screaming fast (Gbit) once their caches are primed.

**Comment by dentarg** [comment]
I've tested the box with Vagrant

```
$ vagrant box add --name "test/openbsd-6.2-amd64" openbsd-6.2-amd64-virtualbox.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'test/openbsd-6.2-amd64' (v0) for provider:
    box: Unpacking necessary files from: file:///Users/dentarg/twingly/boxes/openbsd/openbsd-6.2-amd64-virtualbox.box
==> box: Successfully added box 'test/openbsd-6.2-amd64' (v0) for 'virtualbox'!
```

It boots and runs Ansible, the failure is in our playbook (not up to date for 6.2), so I think we can say the box works!

```
$ vagrant up vagrant-openbsd
Bringing machine 'vagrant-openbsd' up with 'virtualbox' provider...
==> vagrant-openbsd: Importing base box 'test/openbsd-6.2-amd64'...
==> vagrant-openbsd: Matching MAC address for NAT networking...
==> vagrant-openbsd: Setting the name of the VM: ansible_vagrant-openbsd_1512639763392_42212
==> vagrant-openbsd: Clearing any previously set network interfaces...
==> vagrant-openbsd: Preparing network interfaces based on configuration...
    vagrant-openbsd: Adapter 1: nat
==> vagrant-openbsd: Forwarding ports...
    vagrant-openbsd: 8000 (guest) => 8000 (host) (adapter 1)
    vagrant-openbsd: 22 (guest) => 2222 (host) (adapter 1)
==> vagrant-openbsd: Booting VM...
==> vagrant-openbsd: Waiting for machine to boot. This may take a few minutes...
    vagrant-openbsd: SSH address: 127.0.0.1:2222
    vagrant-openbsd: SSH username: vagrant
    vagrant-openbsd: SSH auth method: private key
==> vagrant-openbsd: Machine booted and ready!
==> vagrant-openbsd: Checking for guest additions in VM...
    vagrant-openbsd: No guest additions were detected on the base box for this VM! Guest
    vagrant-openbsd: additions are required for forwarded ports, shared folders, host only
    vagrant-openbsd: networking, and more. If SSH fails on this machine, please install
    vagrant-openbsd: the guest additions and repackage the box to continue.
    vagrant-openbsd:
    vagrant-openbsd: This is not an error message; everything may continue to work properly,
    vagrant-openbsd: in which case you may ignore this message.
==> vagrant-openbsd: Setting hostname...
==> vagrant-openbsd: Running provisioner: shell...
    vagrant-openbsd: Running: inline script
    vagrant-openbsd:  ln -sf /usr/local/bin/python2.7 /usr/bin/python
==> vagrant-openbsd: Running provisioner: ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.2.3.0).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    vagrant-openbsd: Running ansible-playbook...

PLAY [vagrant-openbsd] *********************************************************

TASK [setup] *******************************************************************
ok: [vagrant-openbsd]

TASK [openbsd : include_vars] **************************************************
ok: [vagrant-openbsd]

TASK [openbsd : install working /etc/hosts] ************************************
changed: [vagrant-openbsd]

TASK [openbsd : Install openup] ************************************************
changed: [vagrant-openbsd]

TASK [openbsd : Configure openup.conf] *****************************************
changed: [vagrant-openbsd]

TASK [openbsd : Ensure we have the Mtier public key] ***************************
fatal: [vagrant-openbsd]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find 'mtier-62-pkg.pub' in expected paths."}

PLAY RECAP *********************************************************************
vagrant-openbsd            : ok=5    changed=3    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by jage** [comment]
Released https://app.vagrantup.com/twingly/boxes/openbsd-6.2-amd64/versions/1.0.0

**Pull request merged**
